namespace ArgsRegistry {
  export enum position {
    topLeft = "topLeft",
    topRight = "topRight",
    bottomLeft = "bottomLeft",
    bottomRight = "bottomRight",
  }

  export enum welcomeMessageMode {
    live = "welcomeMessageModeLive",
    beta = "welcomeMessageModeBeta",
    disabled = "welcomeMessageModeDisabled",
  }

  export enum floatingButtonEdge {
    left = "left",
    right = "right",
  }

  export enum colorTheme {
    light = "light",
    dark = "dark",
  }

  export enum strings {
    shakeHint = "shakeHint",
    swipeHint = "swipeHint",
    edgeSwipeStartHint = "edgeSwipeStartHint",
    startAlertText = "startAlertText",
    invalidEmailMessage = "invalidEmailMessage",
    invalidEmailTitle = "invalidEmailTitle",
    invalidCommentMessage = "invalidCommentMessage",
    invalidCommentTitle = "invalidCommentTitle",
    invocationHeader = "invocationHeader",
    reportQuestion = "reportQuestion",
    reportBug = "reportBug",
    reportFeedback = "reportFeedback",
    emailFieldHint = "emailFieldHint",
    commentFieldHintForBugReport = "commentFieldHintForBugReport",
    commentFieldHintForFeedback = "commentFieldHintForFeedback",
    commentFieldHintForQuestion = "commentFieldHintForQuestion",
    videoPressRecord = "videoPressRecord",
    addVideoMessage = "addVideoMessage",
    addVoiceMessage = "addVoiceMessage",
    addImageFromGallery = "addImageFromGallery",
    addExtraScreenshot = "addExtraScreenshot",
    audioRecordingPermissionDeniedTitle = "audioRecordingPermissionDeniedTitle",
    audioRecordingPermissionDeniedMessage = "audioRecordingPermissionDeniedMessage",
    microphonePermissionAlertSettingsButtonText = "microphonePermissionAlertSettingsButtonTitle",
    recordingMessageToHoldText = "recordingMessageToHoldText",
    recordingMessageToReleaseText = "recordingMessageToReleaseText",
    conversationsHeaderTitle = "conversationsHeaderTitle",
    screenshotHeaderTitle = "screenshotHeaderTitle",
    doneButtonText = "doneButtonText",
    okButtonText = "okButtonTitle",
    cancelButtonText = "cancelButtonTitle",
    thankYouText = "thankYouText",
    audio = "audio",
    image = "image",
    screenRecording = "screenRecording",
    team = "team",
    messagesNotification = "messagesNotification",
    messagesNotificationAndOthers = "messagesNotificationAndOthers",
    conversationTextFieldHint = "conversationTextFieldHint",
    collectingDataText = "collectingDataText",
    thankYouAlertText = "thankYouAlertText",
    welcomeMessageBetaWelcomeStepTitle = "welcomeMessageBetaWelcomeStepTitle",
    welcomeMessageBetaWelcomeStepContent = "welcomeMessageBetaWelcomeStepContent",
    welcomeMessageBetaHowToReportStepTitle = "welcomeMessageBetaHowToReportStepTitle",
    welcomeMessageBetaHowToReportStepContent = "welcomeMessageBetaHowToReportStepContent",
    welcomeMessageBetaFinishStepTitle = "welcomeMessageBetaFinishStepTitle",
    welcomeMessageBetaFinishStepContent = "welcomeMessageBetaFinishStepContent",
    welcomeMessageLiveWelcomeStepTitle = "welcomeMessageLiveWelcomeStepTitle",
    welcomeMessageLiveWelcomeStepContent = "welcomeMessageLiveWelcomeStepContent",
    surveysStoreRatingThanksTitle = "surveysStoreRatingThanksTitle",
    surveysStoreRatingThanksSubtitle = "surveysStoreRatingThanksSubtitle",
    reportBugDescription = "reportBugDescription",
    reportFeedbackDescription = "reportFeedbackDescription",
    reportQuestionDescription = "reportQuestionDescription",
    requestFeatureDescription = "requestFeatureDescription",
    discardAlertTitle = "discardAlertTitle",
    discardAlertMessage = "discardAlertMessage",
    discardAlertCancel = "discardAlertCancel",
    discardAlertAction = "discardAlertAction",
    addAttachmentButtonTitleStringName = "addAttachmentButtonTitleStringName",
    reportReproStepsDisclaimerBody = "reportReproStepsDisclaimerBody",
    reportReproStepsDisclaimerLink = "reportReproStepsDisclaimerLink",
    reproStepsProgressDialogBody = "reproStepsProgressDialogBody",
    reproStepsListHeader = "reproStepsListHeader",
    reproStepsListDescription = "reproStepsListDescription",
    reproStepsListEmptyStateDescription = "reproStepsListEmptyStateDescription",
    reproStepsListItemTitle = "reproStepsListItemTitle",
    insufficientContentMessage = "insufficientContentMessage",
    insufficientContentTitle = "insufficientContentTitle",
  }

  export enum reproStepsMode {
    enabled = "enabled",
    disabled = "disabled",
    enabledWithNoScreenshots = "enabledWithNoScreenshots",
  }

  export enum locale {
    arabic = "arabic",
    azerbaijani = "azerbaijani",
    chineseSimplified = "chineseSimplified",
    chineseTraditional = "chineseTraditional",
    czech = "czech",
    danish = "danish",
    dutch = "dutch",
    english = "english",
    finnish = "finnish",
    french = "french",
    german = "german",
    hungarian = "hungarian",
    indonesian = "indonesian",
    italian = "italian",
    japanese = "japanese",
    korean = "korean",
    norwegian = "norwegian",
    polish = "polish",
    portugueseBrazil = "portugueseBrazil",
    portuguesePortugal = "portuguesePortugal",
    romanian = "romanian",
    russian = "russian",
    slovak = "slovak",
    spanish = "spanish",
    swedish = "swedish",
    turkish = "turkish",
  }
}
export = ArgsRegistry;
